name: Deploy Code to EC2

on:
  push:
    branches: ["main"]

jobs:
  Deploy-Code-to-EC2:
    runs-on: hackathon
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Replace '/' with '-' in branch name
        run: echo "::set-output name=formatted_branch::$(echo "${{ steps.extract_branch.outputs.branch }}" | sed 's/\//-/g')"
        id: replace_branch
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Fetch secret from AWS Secret Manager
        run: |
          aws secretsmanager get-secret-value \
            --secret-id "hackathon-env" \
            --query "SecretString" \
            --output text > .env
      - run: npm ci

      - name: Restart PM2 Deployment
        run: pm2 reload ecosystem.config.js && pm2 save